"""Add target_price to FavoriteGame

Revision ID: 53353f9d0889
Revises: 
Create Date: 2026-09-22 22:21:37.566975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53353f9d0889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_game', schema=None) as batch_op:
        batch_op.drop_column('target_price')

    # ### end Alembic commands ###
